language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
  - feature/tests
  - greenkeeper.*
script:
  - yarn build
  - yarn test
  - yarn add firebase-tools
  - npx firebase deploy --token $FIREBASE_TOKEN