language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
  - yarn global add firebase-tools
script:
  - yarn build
  - yarn test:coverage
deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN