language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
  - feature/tests
script:
  - yarn build
before_deploy:
  - yarn test
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^develop|master$
  token:
    secure: GOWNkBFhMYaLxEspsVzWoHojkOhkyS4yEvR+gCRhmjRFtwdgbgrPi7iellotDeM4qjZF+/BVqNXuTy5q0ThhVkjHJApOCRSYABntyCYOZ6MYqhIu6Ju4b6M6JtLm1XpVNozD9rUg82MFnCMfYUvWn3pHVvW65iPf0klyMbtCC0hgVhon3/CvXkGEvGnGxyN6DclfYuHm+7Bxrl2EYhPY9TzmvNJq7kIwf7FiAMI5RZ2/6tqYROIIH/ZNgIbTG44ki4IbrAXzexH9PEoBTbXgvWPsk+8oMPg2AvqRljc7YVaiV6uD/wpOboj2Ruuy/ybcAvSwnwEae6DYD+8AqoUWOb0wxqRbu/xY5rj4KfAhUPWGWyhZxW+4mzzlBFcJBaUpVE1Hmo7Z2ws8ZVAZX3i3Dn5OjbbTOcETXKOOsGhJnU0jMc6x+hgI81NeHY+NE9lxgXtkhgqgeoXFnBbZLiY4Jv+aobg7Bixv/6Kr0r4cT+RbkrVNk9876gjKEFTXAKwgBg1uEd9Q3NX1wi3x+5kWXx+g7Fqx2YuMFzJifSRMmFd6YqacSwJdE9DCfmddEmkkDqd7ueB5QPN8fz2jF5CblRMFZRZF5adw6JyRPQMsLlbiN2sBQEkSexDmWfUHt01NukVKSsIawrih9FZmwAZ26cxnGMkPgbf4do3uk4iGKI4=